console.log("Math.E:", Math.round(Math.E));
console.log("Math.LN10:", Math.floor(Math.LN10));
console.log("Math.LN2:", Math.floor(Math.LN2));
console.log("Math.LOG10E:", Math.round(Math.LOG10E));
console.log("Math.LOG2E:", Math.round(Math.LOG2E));
console.log("Math.PI:", Math.round(Math.PI));
console.log("Math.SQRT1_2:", Math.round(Math.SQRT1_2));
console.log("Math.SQRT2:", Math.round(Math.SQRT2));

console.log("Math.abs:", Math.round(Math.abs(-42)));
console.log("Math.acos:", Math.round(Math.acos(0.5)));
console.log("Math.acosh:", Math.round(Math.acosh(2)));
console.log("Math.asin:", Math.round(Math.asin(0.5)));
console.log("Math.asinh:", Math.round(Math.asinh(1)));
console.log("Math.atan:", Math.round(Math.atan(0.5)));
console.log("Math.atanh:", Math.round(Math.atanh(0.5)));
console.log("Math.atan2:", Math.round(Math.atan2(1, 2)));
console.log("Math.cbrt:", Math.round(Math.cbrt(27)));
console.log("Math.ceil:", Math.ceil(41.1));
console.log("Math.cos:", Math.round(Math.cos(Math.PI)));
console.log("Math.cosh:", Math.round(Math.cosh(0)));
console.log("Math.exp:", Math.round(Math.exp(1)));
console.log("Math.floor:", Math.floor(41.9));
console.log("Math.log:", Math.round(Math.log(10)));
console.log("Math.max:", Math.round(Math.max(5, 2, 8, 1)));
console.log("Math.min:", Math.round(Math.min(5, 2, 8, 1)));
console.log("Math.pow:", Math.round(Math.pow(2, 3)));
let randomValue = Math.round(Math.random());
console.log("Math.round:", Math.round(41.5));
console.log("Math.sign:", Math.sign(-3));
console.log("Math.sin:", Math.round(Math.sin(Math.PI / 6)));
console.log("Math.sinh:", Math.round(Math.sinh(0)));
console.log("Math.sqrt:", Math.round(Math.sqrt(25)));
console.log("Math.tan:", Math.round(Math.tan(Math.PI / 4)));
console.log("Math.tanh:", Math.round(Math.tanh(0)));
console.log("Math.trunc:", Math.floor(42.9));
